gif_config:
  common:
    font_size: 32
    font_family: JetBrains Mono

  gifs:
    - name: 'dark'
      theme: 'monokai'
    - name: 'light'
      theme: 'solarized_light'

scenario:
  # Wait for the first message and wait 1.5 seconds to read the message
  - expect: \n
  - wait: 1500

  # Write "Ilya"
  - write: "Ilya"

  # Wait for the second message and wait 1.5 seconds to read the message
  - expect: \n
  - wait: 1500

  # Write "21" sloooooowly
  - delay: 2000
  - write: "21"

  # Restore default delay
  - delay: 50

  # Wait for the last message
  - expect: \n
